spring:
  profiles:
    include:
      - comm
---
api:
  common:
    version: 1.0.0
    title: Profile Box User API
    description: Profile Box User API
    termsOfServiceUrl: ㅇ
    license: License
    licenseUrl: MY LICENSE URL
    contact:
      name: Contact
      url: My
      email: me@mail.com

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
---
server:
  config:
    activate:
      on-profile: prod
  port: 8080
  error.include-message: always
  tomcat:
    max-swallow-size: -1
#  host:
#    adminApi: https://profile-box-api-admin.api-admin.svc.cluster.local:8080

logging:
  config:
    activate:
      on-profile: prod
  level:
    root: ERROR
---
server:
  config:
    activate:
      on-profile: local
  port: 7001
  error.include-message: always
  tomcat:
    max-swallow-size: -1

logging:
  config:
    activate:
      on-profile: local
  level:
    root: DEBUG

custom:
  config:
    activate:
      on-profile: local
  host:
    authApi: http://localhost:7002
